---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Provider
metadata:
  name: github-instavote
  namespace: flux-system
spec:
  address: https://github.com/khopkins32/instavote
  secretRef:
    name: github-token
  type: github
