---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: result
  namespace: instavote
spec:
  exclusionList:
  - ^.*\.sig$
  image: khopkins32/result
  interval: 1m0s
  provider: generic
