---
apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImageUpdateAutomation
metadata:
  annotations:
    reconcile.fluxcd.io/requestedAt: "2023-10-01T18:18:54.825606705Z"
  name: instavote-all
  namespace: flux-system
spec:
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        email: khopkins32@gmail.com
        name: flux
      messageTemplate: '{{range .Updated.Images}}{{println .}}{{end}}'
    push:
      branch: main
  interval: 1m0s
  sourceRef:
    kind: GitRepository
    name: instavote
  update:
    path: ./deploy/vote/staging
    strategy: Setters
