apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
patchesStrategicMerge:
- deployment.yaml
- service.yaml
namespace: instavote
images:
  - name: schoolofdevops/vote
    newName: khopkins32/vote
    newTag: v4 # {"$imagepolicy":"flux-system:vote:tag"}
replicas:
  - name: vote
    count: 4
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "khopkins32@gmail.com"
configMapGenerator:
  - name: vote
    literals:
      - OPTION_A=FluxCD
      - OPTION_B=ArgoCD
